language: cpp
sudo: required
compiler: gcc
env: QT_BASE="512"
cache: bundler
group: deprecated-2017Q4
before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial -y;
    - sudo apt-get update -qq;
    - sudo apt-get install mesa-common-dev;
    - sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev;
install:
    - sudo apt-get install -qq qt512-meta-minimal; source /opt/qt512/bin/qt512-env.sh;

script:
    - qmake
    - make
notifications:
    email: true